name: Create EC2 Instance
 on:

  push:

    branches:

      - main
 
jobs:

  create-ec2:

    runs-on: ubuntu-latest
 
    steps:

      - name: Checkout Repository

        uses: actions/checkout@v2
 
      - name: Setup AWS CLI

        uses: aws-actions/configure-aws-credentials@v2

        with:

          aws-access-key-id: ${{ secrets.AKIATPAKWB7K6IR723XG}}

          aws-secret-access-key: ${{ secrets.sinyCir6da0uDRAuAsQoknmHQe4C84qM/JyoBZvv}}

          aws-region: your-preferred-region
 
      - name: Create EC2 Instance

        run: |

          # Use AWS CLI or SDK to create an EC2 instance here

          # Example:

          # aws ec2 run-instances --image-id ami-xxxxxxxx --instance-type t2.micro --key-name your-key-pair
