name: Create EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  create-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
         aws-access-key-id: ${{ secrets.AKIATPAKWB7K6IR723XG }}
         aws-secret-access-key: ${{ secrets.sinyCir6da0uDRAuAsQoknmHQe4C84qM/JyoBZvv }}
         aws-region: ${{ secrets.us-east-1 }}

      - name: Create EC2 Instance
        run: |
          # Use AWS CLI to create an EC2 instance
          aws ec2 run-instances \
            --image-id ami-0005e0cfe09cc9050 \
            --instance-type t2.micro \
            --key-name hemakey \
            --subnet-id subnet-01cdfa5b762c5723e \
            --security-group-ids sg-0a1004adb2e93c08b \
            --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=Github}]"
