name: Create EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  create-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
         aws-region: ${{ secrets.AWS_REGION }}

      - name: Create EC2 Instance
        run: |
          # Use AWS CLI to create an EC2 instance with user data
          aws ec2 run-instances \
            --image-id ami-0005e0cfe09cc9050 \
            --instance-type t2.micro \
            --key-name hemakey \
            --subnet-id subnet-03cea030789b37116 \
            --security-group-ids sg-025e8d9ed9a75362a \
            --user-data "$(base64 -w 0 userdata.sh)" \
            --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=Github}]"
